### ISSUE TITLE
Slots for previous, next and close buttons

### ISSUE THREAD

**Issue by keesvanlierop** [DCzajkowski/vue-pure-lightbox#13]
I would like to use my own custom SVG elements for the control buttons inside the lightbox, instead of the icons that are provided from within this package. I have a PR ready, but it seems I cannot push to any new branch.

**Comment by DCzajkowski** [comment]
Hello @keesvanlierop!

If you want to make a PR to any repository on GitHub that is not yours, you have to follow these steps:
1. Press "Fork" in the upper right corner. It will create a repository copy on your account.
2. Clone **your** repository copy
3. Edit and commit to whatever branch
4. Push changes
5. Go to GitHub to the repository you forked and press "New pull request"


In your case, as you already have made changes, follow these steps:
1. Press "Fork" in the upper right corner. It will create a repository copy on your account.
2. Copy url from the "Clone or download" button in your account copy
3. Go to terminal and paste `git remote add my [here paste the url]` — it will add a new remote
4. Paste `git push my [branch name here (can be master)]`
5. Push changes with `git push`
5. Go to GitHub to https://github.com/DCzajkowski/vue-pure-lightbox/pulls and press "New pull request"

**Comment by keesvanlierop** [comment]
Ah, yes, thanks! Created #14
