### ISSUE TITLE
The demo on codepen.io seems to be broken

### ISSUE THREAD

**Issue by RohanTalip** [DCzajkowski/vue-pure-lightbox#18]
It's getting a 404 for https://unpkg.com/vue-pure-lightbox@3.1.0/dist/vue-pure-lightbox.css

**Comment by DCzajkowski** [comment]
Yes, the new version introduces some breaking changes, one of them being a new name for the JS and CSS files: https://unpkg.com/vue-pure-lightbox@3.1.0/dist/VuePureLightbox.css

**Comment by DCzajkowski** [comment]
I though I have updated all codepen demos. Can you send a link to the broken one?

**Comment by RohanTalip** [comment]
It's the one in the description for this project and is the same one in the README.md file:
https://codepen.io/DCzajkowski/pen/rzOErW

**Comment by DCzajkowski** [comment]
Updated. Thanks!
