### ISSUE TITLE
Thumbnail image in the demo is broken

### ISSUE THREAD

**Issue by callumflack** [DCzajkowski/vue-pure-lightbox#21]
`https://bit.ly/2rQZxUf` from the demo in your README, https://codepen.io/DCzajkowski/pen/rzOErW

**Comment by DCzajkowski** [comment]
Can you link me some nice cat pictures with simple urls we could use? 😊

**Comment by callumflack** [comment]
[Sure.](https://www.dropbox.com/s/zypeygs2x8xvokj/cat_picture.jpg?dl=0) Can't say it'll live forever in my dropbox tho… 😊

**Comment by SiamKreative** [comment]
Heya! I think this is a great little library but it's a shame the demo is still not working. Perhaps you can use https://placekitten.com/ :)

**Comment by DCzajkowski** [comment]
Fixed!
