### ISSUE TITLE
Ability to use custom video's (MP4)

### ISSUE THREAD

**Issue by Cannonb4ll** [DCzajkowski/vue-pure-lightbox#23]
Hi!

Would it be possible (or maybe it is already?) to support self-hosted MP4's? I currently have my own video's and I don't want to upload them all to youtube.

Thanks!

**Comment by DCzajkowski** [comment]
Yes, it's possible!

```vue
<VuePureLightbox
  thumbnail="https://via.placeholder.com/350x150"
  :images="[
    { link: 'your-video-link, type: 'video' },
  ]"
>
  <div v-slot:loader>Loading…</div>
  <div v-slot:content="{ url: { link, type } }">
    <video :src="link" v-if="type === 'video'">
  </div>
</VuePureLightbox>
```

**Comment by Cannonb4ll** [comment]
Oh very nice! I was not able to find this back in the documentation. Thank you so much, will be using that.

**Comment by DCzajkowski** [comment]
No problem :)
