### ISSUE TITLE
youtube video popup

### ISSUE THREAD

**Issue by uzzal-ht** [DCzajkowski/vue-pure-lightbox#29]
How to use YouTube video popup with custom play button ?

**Comment by DCzajkowski** [comment]
Have you seen #7 and #23?

**Comment by uzzal-ht** [comment]
If possible share a component with YouTube video popup by click button as like image popup.
I can't use it.
Example images below here.....
[https://prnt.sc/t6shw4](https://prnt.sc/t6shw4)

**Comment by DCzajkowski** [comment]
Here is a demo with stock YT player: https://jsfiddle.net/6bt29avm/4/. If you want some custom player icons you'll have to implement them yourself.
