### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by cyberiaa** [DCzajkowski/vue-pure-lightbox#4]
Hi,

Thank you for your great work.

Do you have any plan for a simple loading indicator? When one click on next button there is no feedback for user so they try it again and again. Really confusing for slow connection. A simple loading indicator maybe helpful.

Thanks again!

**Comment by DCzajkowski** [comment]
I think it's a great idea and actually something I wanted to implement a while back. I don't want to break backwards compatibility, so I have a great idea how to implement it. I'll give it a shot maybe even today 😉

**Comment by cyberiaa** [comment]
That's great!

**Comment by DCzajkowski** [comment]
As of v2.1.5 you can use your custom, or built-in loader like so:
```html
<lightbox
    thumbnail="/path/to/thumbnail.jpg"
    :images="['/path/to/image1.jpg', '/path/to/image1.jpg']"
>
    <lightbox-default-loader slot="loader"></lightbox-default-loader> <!-- If you want to use built-in loader -->
    <!-- <div slot="loader"></div> --> <!-- If you want to use your own loader -->
</lightbox>
```
