### ISSUE TITLE
allow more thumbnails

### ISSUE THREAD

**Issue by nikola-pavlovic** [DCzajkowski/vue-pure-lightbox#8]
Maybe adding a prop `showAllThumbs`, for displaying single/all thumbnails, would make a difference...at least for me :)
cao

**Comment by DCzajkowski** [comment]
Hey, a purpose of this package is to allow showing one thumbnail with multiple images in a carousel. If you want more customizability, you can always fork this project or look for a more advanced libraries [here](https://github.com/vuejs/awesome-vue#overlay).
