### ISSUE TITLE
alternate-text alt tag only applied to thumbnail

### ISSUE THREAD

**Issue by graneyc** [DCzajkowski/vue-pure-lightbox#9]
Currently, there doesn't seem to be a great way to get an alt tag on the expanded lightbox image(s).

I understand that there is difficulty in that the expanded images are built from an array, but what if we made that array more complex so we could pass in src and alt for the expanded ligthbox image(s)?

Is there some way of doing this using the slot loader that I'm missing?

**Comment by DCzajkowski** [comment]
I really resist to add any additional options, parameters etc, as it greatly increases complexity, but I agree, that `alt` attribute is something we should have. I will try to work on some nice, not-breaking change solution.

**Comment by DCzajkowski** [comment]
Hey, actually it is currently supported using the scoped slot: [usage](https://codepen.io/DCzajkowski/pen/jdgEJV)
